FROM python:3.9-slim  # Use Python version compatible with your dependencies

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN apt-get update && \
    apt-get install -y procps && \
    pip install -U pip && \
    pip install -r ./requirements.txt

COPY ./main.py /code/

EXPOSE 8001

CMD ["uvicorn","main:app", "--host", "0.0.0.0", "--port", "8001"]
