# Usar la imagen oficial de Python 3.8 slim como base
FROM python:3.8-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Instalar MLflow, PostgreSQL adapter y apprise
RUN pip install --no-cache-dir mlflow==2.7.0 psycopg2-binary apprise

# Exponer el puerto 5000 para el servidor de MLflow
EXPOSE 5000

# Establecer el comando de entrada para ejecutar el servidor de MLflow
ENTRYPOINT ["mlflow", "server"]