FROM python:3.11-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN apt-get update && \
    apt-get install -y procps && \
    pip install -U pip && \
    pip install -r ./requirements.txt

COPY ./main.py /code/

EXPOSE 8502

CMD ["streamlit", "run", "main.py", "--server.port", "8502", "--server.address", "0.0.0.0"]
