# version: '3.8'

services:
  ui:
    image: laliga-ui-image:latest
    container_name: laliga-ui-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8502:8502"
    depends_on:
      - model
    networks:
      - laliga-network

  model:
    image: laliga-model-image:latest
    container_name: laliga-model-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - laliga-network

networks:
  laliga-network:
    name: laliga-network-1
    driver: bridge
